apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: akpub
  annotations:
    github.com/project-slug: krishashokk/akpub
spec:
  type: other
  lifecycle: experimental
  owner: abc
  security: public
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
      security: public
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
