apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: akpub
  annotations:
    github.com/project-slug: krishashokk/akpub
spec:
  type: other
  lifecycle: experimental
  owner: abc
  security: public
  definition: |
    title: Hello world # required title
     /greeting: # optional resource
     get: # HTTP method declaration
       responses: # declare a response
         200: # HTTP status code
          body: # declare content of response
            application/json: # media type
            # structural definition of a response (schema or type)
            type: object
            properties:
              message: string
            example: # example how a response looks like
              message: "Hello world"
